voxpupuli/puppet-collectd

- README.md
- manifests/plugin/lvm.pp
This add the lvm plugin support.
> added lvm plugin

- templates/plugin/snmp.conf.erb
otherwise if you don't pass in an array you get a really awful error :)
> arrayify the values and collects

- manifests/plugin/amqp.pp
- manifests/plugin/bind.pp
- manifests/plugin/curl.pp
- manifests/plugin/curl_json.pp
- manifests/plugin/iptables.pp
- manifests/plugin/mysql.pp
- manifests/plugin/nginx.pp
- manifests/plugin/perl.pp
- manifests/plugin/ping.pp
- manifests/plugin/postgresql.pp
- manifests/plugin/python.pp
- manifests/plugin/sensors.pp
- manifests/plugin/snmp.pp
- manifests/plugin/varnish.pp
- manifests/plugin/write_http.pp
- manifests/plugin/write_riemann.pp
- templates/plugin/snmp.conf.erb
This should add the necessary packages for plugins on redhat derived systems.
It should also fix #148.
> Add redhat packages on plugins

- manifests/plugin/snmp.pp
- manifests/plugin/snmp/data.pp
- manifests/plugin/snmp/host.pp
- spec/classes/collectd_plugin_snmp_spec.rb
- spec/defines/collectd_plugin_snmp_data_spec.rb
- spec/defines/collectd_plugin_snmp_host_spec.rb
- templates/plugin/snmp/data.conf.erb
- templates/plugin/snmp/host.conf.erb
this will make it a lot easier to have a "centralized" collectd snmp
collector that will gather information from network devices and such
which are puppetized but don't run their own collectd :)
> split out the snmp data and hosts into defines

- metadata.json
- soften PE version requirement
- remove deprecated 'description' field
> metadata update

- README.md
please review for eventual broken english
> Add a section to explain version scoping & known issue for #162

- Gemfile
- Gemfile.lock
- metadata.json
Added gem required for meta data lint and changed license name to SPDX format.
> Fix module meta data

- manifests/plugin/statsd.pp
- templates/plugin/statsd.conf.erb
Mirrored additional configuration parameters to puppet configuration module.
Please refer to https://github.com/collectd/collectd/pull/403
> Added absent timers for statsd module.

- README.md
- manifests/plugin/cpu.pp
- spec/classes/collectd_plugin_cpu_spec.rb
- templates/plugin/cpu.conf.erb
This makes new cpu options configurable, see https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_cpu
> add new cpu plugin options introduced in collectd 5.5

- README.md
- manifests/plugin/protocols.pp
- spec/classes/collectd_plugin_protocols_spec.rb
- templates/plugin/protocols.conf.erb
Adding support for the protocols plugin might be useful for others
> add support for protocols plugin

- .travis.yml
- CHANGELOG.md
- metadata.json
This release fixes .travis.yml so deploys work
> Release 4.1.1

- README.md
Two sections were mixed with each other:
* Class: collectd::plugin::processes
* Class: collectd::plugin::protocols
> Small fix in documentation.

- README.md
- manifests/plugin/netlink.pp
- spec/classes/collectd_plugin_netlink_spec.rb
- templates/plugin/netlink.conf.erb
- tests/plugins/netlink.pp
I need the netlink plugin to get detailed network interface stats:
- https://collectd.org/wiki/index.php/Plugin:Netlink
I've based it on `collectd::plugin::interface`
I will add short docs and will try to write rspec tests.
> Added plugin::netlink

- README.md
- manifests/plugin/ceph.pp
- spec/classes/collectd_plugin_ceph_spec.rb
- templates/plugin/ceph.conf.erb
- tests/plugins/ceph.pp
Class to manage ceph plugin for collectd
> add collectd::plugin::ceph

- manifests/init.pp
- templates/collectd.conf.erb
> Add support for CollectInternalStats

- README.md
- manifests/plugin/write_sensu.pp
- templates/plugin/write_sensu.conf.erb
It would be a nice to have the plugin write sensu availlable.
https://collectd.org/wiki/index.php/Plugin:Write_Sensu
Thanks a lot in advance for your comments and inputs.
> Added plugin write_sensu

- README.md
- manifests/plugin/dbi.pp
- manifests/plugin/dbi/database.pp
- manifests/plugin/dbi/query.pp
- spec/classes/collectd_plugin_dbi_spec.rb
- templates/plugin/dbi/database.conf.erb
- templates/plugin/dbi/query.conf.erb
This adds the collectd plugin DBI
> Add Plugin DBI

- spec/classes/collectd_init_spec.rb
- templates/collectd.conf.erb
> fix class tests

- templates/curl_json.conf.erb
by sorting the keys! (original patch by @miroth70)
this closes issue #334
> idempotence: make output deterministic in curl_json

- manifests/plugin/mysql/database.pp
#355 removed if statement becouse MySQL supports Master/Master replication where each Master is also a slave and you probably want both.
> #355 Removed Master/Slave if statement

- manifests/init.pp
fix collectd_real_version regex
> fix collectd_real_version regex

- manifests/plugin/amqp.pp
- manifests/plugin/apache.pp
- manifests/plugin/bind.pp
- manifests/plugin/curl.pp
- manifests/plugin/iptables.pp
- manifests/plugin/libvirt.pp
- manifests/plugin/lvm.pp
- manifests/plugin/mysql.pp
- manifests/plugin/nginx.pp
- manifests/plugin/perl.pp
- manifests/plugin/ping.pp
- manifests/plugin/postgresql.pp
- manifests/plugin/sensors.pp
- manifests/plugin/snmp.pp
- manifests/plugin/varnish.pp
- manifests/plugin/write_riemann.pp
- manifests/plugin/write_sensu.pp
This fixes a bug that I introduced in https://github.com/puppet-community/puppet-collectd/pull/341 (wrong variable assignment)
> fix $manage_package param

- .rspec
- .travis.yml
- README.md
- metadata.json
Please merge. Just some minor changes, regarding modulesync_config and renaming from puppet-community to voxpupuli.
> Update based on voxpupuli/modulesync_config

- CHANGELOG.md
- CONTRIBUTING.md
- metadata.json
Please merge. This closes #401.
> Update module to version 4.3.0

- manifests/plugin/amqp.pp
- templates/plugin/amqp.conf.erb
> Add parameter StoreRates to amqp plugin

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/collectd_init_spec.rb
Allows you to set the collectd config file with a custom string/template
> Adds ability to set config content explicitly

- manifests/plugin/python.pp
> Manage the collectd-python package

- manifests/plugin/curl_json.pp
- spec/defines/collectd_plugin_curl_json_spec.rb
- templates/curl_json.conf.erb
* add param $header = undef to collectd::plugin::curl_json
* add new param to collectd_plugin_curl_json_spec.rb
* add rspec test for collectd::plugin::curl_json
> add optional header param for collectd::plugin::curl_json

- manifests/plugin/aggregation.pp
- manifests/plugin/curl.pp
- manifests/plugin/curl_json.pp
- manifests/plugin/dbi.pp
- manifests/plugin/dns.pp
- manifests/plugin/genericjmx.pp
- manifests/plugin/java.pp
- manifests/plugin/netlink.pp
- manifests/plugin/postgresql.pp
- manifests/plugin/rrdcached.pp
- manifests/plugin/rrdtool.pp
- spec/classes/collectd_plugin_dns_spec.rb
> Manage all the plugins that have external packages

- templates/plugin/df.conf.erb
> ReportsReserved only exists in the df plugin before 5.5. Fixes #435

- CHANGELOG.md
- manifests/plugin/disk.pp
- spec/classes/collectd_plugin_disk_spec.rb
> Ensure collectd-disk exists on RedHat and collectd >= 5.5

- .rubocop.yml
- .travis.yml
- Rakefile
> Update from voxpupuli modulesync_config

- README.md
- manifests/plugin/write_kafka.pp
- spec/classes/collectd_plugin_write_kafka_spec.rb
- templates/plugin/write_kafka.conf.erb
This PR adds support for the [write_kafka](https://collectd.org/wiki/index.php/Plugin:Write_Kafka) plugin.
> add write_kafka support

- CHANGELOG.md
- README.md
- manifests/plugin/virt.pp
- spec/classes/collectd_plugin_virt_spec.rb
- templates/plugin/virt.conf.erb
> Rename libvirt to virt

- templates/tail-file.conf.erb
Tail plugin has an option to also set ExcludeRegex.
I tried adding a test as well, but I'm having some troubles. Will try some more and commit when I'll have something useful.
I also can't find a good case for documentation.
> Add ExcludeRegex option to tail module

- README.md
There was a little typo in README.md.
> Fix a typo in fhcount sample

- templates/tail-file.conf.erb
Reverts voxpupuli/puppet-collectd#507
> Revert "Only set ExcludeRegex in config file if variable is defined"

- templates/tail-file.conf.erb
Previous if statement was wrong, now it's working as it should...
> Only set ExcludeRegex when needed (fix for #507)

- manifests/config.pp
- manifests/init.pp
- spec/classes/collectd_init_spec.rb
Also add validation for most of the other parameters.
> Add spec test for 'has_wordexp' and validate_bool

- .msync.yml
- .rubocop.yml
- .travis.yml
- CHANGELOG.md
- Gemfile
- metadata.json
- spec/classes/collectd_plugin_ping_spec.rb
- spec/classes/collectd_plugin_python_spec.rb
- spec/spec_helper.rb
> Modulesync 0.12.1 & Release 5.1.0

- manifests/plugin/tail.pp
ex:
collectd::plugin::tail::files:
'somelog':
filename: '/var/log/logfile'
instance: 'lookingforsomething'
matches:
- regex:    'connected'
dstype:   'CounterInc'
type:     'counter'
instance: 'connection-open'
- regex:    'disconnect'
dstype:   'CounterInc'
type:     'counter'
instance: 'connection-close'
> add ability to add files via hiera

- .gitignore
- .msync.yml
- .travis.yml
- Gemfile
- Rakefile
- manifests/plugin/ceph.pp
- manifests/plugin/rabbitmq.pp
- manifests/plugin/tail.pp
@bastelfreak Let us wait for Travis CI and merge as usual. ;)
> Update based on voxpupuli/modulesync_config 0.12.6

- README.md
> Added missing quote

- README.md
- examples/plugins/memcached.pp
- manifests/plugin/memcached.pp
- spec/classes/collectd_plugin_memcached_spec.rb
- templates/plugin/memcached.conf.erb
This also adds support for memcached via sockets.
> support for multiple instances for memcached

- manifests/plugin/aggregation/aggregator.pp
- templates/plugin/aggregation-aggregator.conf.erb
> Change type parameter to agg_type. Type is a reserved word in puppet.

- .fixtures.yml
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- metadata.json
- spec/classes/collectd_init_spec.rb
- spec/defines/collectd_plugin_apache_instance_spec.rb
- spec/defines/collectd_plugin_curl_json_spec.rb
- spec/defines/collectd_plugin_curl_page_spec.rb
- spec/defines/collectd_plugin_exec_cmd_spec.rb
- spec/defines/collectd_plugin_filecount_directory_spec.rb
- spec/defines/collectd_plugin_filter_chain_spec.rb
- spec/defines/collectd_plugin_filter_match_spec.rb
- spec/defines/collectd_plugin_filter_rule_spec.rb
- spec/defines/collectd_plugin_filter_target_spec.rb
- spec/defines/collectd_plugin_genericjmx_connection_spec.rb
- spec/defines/collectd_plugin_genericjmx_mbean_spec.rb
- spec/defines/collectd_plugin_mysql_database_spec.rb
- spec/defines/collectd_plugin_python_module_spec.rb
- spec/defines/collectd_plugin_snmp_data_spec.rb
- spec/defines/collectd_plugin_snmp_host_spec.rb
- spec/defines/collectd_plugin_spec.rb
- spec/defines/collectd_plugin_tail_file_spec.rb
- spec/defines/collectd_typesdb_spec.rb
- spec/spec_helper_acceptance.rb
Get latest version of collectd including plugins
> Add apt repo

- manifests/plugin/rabbitmq.pp
> Added provider_proxy for pip

- manifests/plugin/interface.pp
- spec/classes/collectd_plugin_interface_spec.rb
- templates/plugin/interface.conf.erb
Another PR that adds ReportInactive support to interface plugin
> Add support for Interface plugin option ReportInactive

- .gitignore
- .msync.yml
- .rubocop.yml
- Gemfile
- spec/acceptance/nodesets/docker/centos-5.yml
- spec/acceptance/nodesets/docker/centos-6.yml
- spec/acceptance/nodesets/docker/centos-7.yml
- spec/acceptance/nodesets/docker/debian-7.yml
- spec/acceptance/nodesets/docker/debian-8.yml
- spec/acceptance/nodesets/docker/ubuntu-12.04.yml
- spec/acceptance/nodesets/docker/ubuntu-14.04.yml
- spec/acceptance/nodesets/docker/ubuntu-16.04.yml
- spec/classes/collectd_plugin_cpu_spec.rb
- spec/classes/collectd_plugin_interface_spec.rb
- spec/spec_helper.rb
> modulesync 0.15.0

- manifests/install.pp
Missing ordering logic for ppa on Ubuntu
> Ensure ppa is applied before package is installed

- spec/defines/collectd_plugin_genericjmx_mbean_spec.rb
- templates/plugin/genericjmx/mbean.conf.erb
> Allow multiple genericjmx mbean attribute entries

- README.md
- examples/plugins/write_prometheus.pp
- manifests/plugin/write_prometheus.pp
- spec/classes/collectd_plugin_write_prometheus_spec.rb
- templates/plugin/write_prometheus.conf.erb
**Only support in collectd 5.7 and later**
Adds support for the write_prometheus plugin.
Minor tidy'ing of the README too.
> Added write_prometheus plugin

- README.md
- examples/plugins/snmp.pp
- spec/classes/collectd_plugin_snmp_spec.rb
- templates/plugin/snmp.conf.erb
Changes the case on all instances of the collectd::plugin::snmp to be snake_case. Fixes #580
> Changed casing to be standard snake_case for collectd::plugin::snmp

- manifests/plugin/write_riemann.pp
- spec/classes/collectd_plugin_write_riemann_spec.rb
- templates/plugin/write_riemann.conf.erb
1. Added the CheckThresholds attribute and updated tests.
2. Fixed incorrect reference in test.
> Updates to write_riemann

- README.md
- manifests/plugin/threshold.pp
- spec/classes/collectd_plugin_threshold_spec.rb
tl;dr - will try to add a template for thresholds at some point too.
> Added base threshold plugin

- templates/plugin/perl/plugin.erb
> Use sort on hashes in template perl/plugin.erb

- README.md
- manifests/plugin/df.pp
- spec/classes/collectd_plugin_df_spec.rb
- templates/plugin/df.conf.erb
df plugin has had Device parameter about 10 years,
https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_df
https://collectd.org/wiki/index.php/Plugin:DF
add support for it as devices parameter
> df: add devices parameter

- README.md
- manifests/plugin/iscdhcp.pp
- spec/classes/collectd_plugin_iscdhcp_spec.rb
> Added ISC DHCP pool metrics plugin

- README.md
- spec/classes/collectd_plugin_postgresql_spec.rb
- templates/plugin/postgresql/query.conf.erb
> Fix writing of postgresql query params and add a test

- manifests/plugin/amqp.pp
- templates/plugin/amqp.conf.erb
Trivial pull request adding support of the amqp option "routingkey"
> collectd::plugin::amqp is now supporting the routingkey option

- .msync.yml
- Rakefile
- spec/acceptance/nodesets/docker/centos-7.yml
- spec/acceptance/nodesets/docker/debian-8.yml
- spec/acceptance/nodesets/docker/ubuntu-12.04.yml
- spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml
- spec/acceptance/nodesets/ec2/image_templates.yaml
- spec/acceptance/nodesets/ec2/rhel-73-x64.yml
- spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml
- spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml
- spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml
> modulesync 0.20.1

- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
> modulesync 0.22.0

- metadata.json
This seems to require no changes on collectd's side.
> bump version on puppetlabs/apt dependency

- spec/classes/collectd_plugin_zookeeper_spec.rb
> Fix zookeeper tests

- manifests/plugin/curl/page.pp
- spec/classes/collectd_plugin_curl_spec.rb
- Also fix mismatched verifyhost test value
> plugin::curl - Use data types

- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
- spec/acceptance/nodesets/docker/debian-7.yml
- spec/acceptance/nodesets/docker/debian-9.yml
> modulesync 1.4.1

- README.md
- manifests/plugin/mysql/database.pp
- templates/mysql-database.conf.erb
https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_mysql
> plugin/mysql: optional wsrepstats setting

- manifests/plugin/mysql/database.pp
- Also directly use $collectd::plugin_conf_dir
> plugin::mysql::database - Add data type

- manifests/plugin/filter/rule.pp
> plugin::filter::rule - add data type

- manifests/plugin/filter/match.pp
- types/filter/match.pp
> plugin::filter::match - Use data types

- README.md
- manifests/plugin/perl/plugin.pp
- manifests/plugin/rabbitmq.pp
> replace topscope variables with facts hash

- manifests/plugin/filter.pp
> Remove duplicate 'include'

- .msync.yml
- Gemfile
> modulesync 1.7.1

- .travis.yml
> add ruby 2.5.0 to the testmatrix

- manifests/init.pp
- types/manifests/init.pp
> update version for collectd package

- .sync.yml
- .travis.yml
> generate acceptance tests by modulesync

- CHANGELOG.md
- metadata.json
> release 8.3.0

- manifests/service.pp
Use variables directly from the init.pp
> Remove parameters from collectd::service class

- README.md
- manifests/plugin/nut.pp
- manifests/plugin/nut/ups.pp
- spec/classes/collectd_plugin_nut_spec.rb
- templates/plugin/nut/ups.conf.erb
This is a rebase of @amishHammer PR #621 against current master but without the change to the types.db handling and with a fix for the linter warning. It also includes a spec test (which might need some additions).
> Add support for nut plugin (#621)

- CHANGELOG.md
- metadata.json
> release 9.0.1

- CHANGELOG.md
- metadata.json
> release 9.1.0

- CHANGELOG.md
- metadata.json
> release 10.0.0

- README.md
This PR updates the **README.md** example documentation for the `collectd::plugin::write_riemann` class to match the updated class and template parameters.
N/A
> update README example for plugin::write_riemann

- README.md
As per https://github.com/voxpupuli/puppet-collectd/issues/841 update documentation with an example for collectd::plugin::ping that has been tested to succeeded
Fixes #841
> Update collectd::plugin::ping example with an example that has been tested to succeeded

- .fixtures.yml
- .github/CONTRIBUTING.md
- .msync.yml
- .travis.yml
- Gemfile
- spec/defines/collectd_plugin_curl_json_spec.rb
> modulesync 2.1.0 and allow puppet 6.x

- metadata.json
> allow puppet 6.x

- CHANGELOG.md
- metadata.json
> release 10.1.0

- .sync.yml
- .travis.yml
- manifests/params.pp
- metadata.json
- spec/spec_helper_methods.rb
> add Ubuntu 18.04 support

- manifests/plugin.pp
- spec/defines/collectd_plugin_spec.rb
- templates/loadplugin.conf.erb
Adds an optional param: FlushInterval to the loadplugin config
n/a
> add flushinterval param to loadplugin config

- .msync.yml
- .sync.yml
- .travis.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 2.7.0

- metadata.json
> drop EOL Ubuntu 14.04

- CHANGELOG.md
- metadata.json
> release 11.0.0

- .travis.yml
> travis: switch base OS from xenial to bionic

- .sync.yml
- .travis.yml
> drop Ubuntu 14.04 support

- manifests/plugin/filecount.pp
- manifests/plugin/openvpn.pp
- manifests/plugin/perl/plugin.pp
Fixed stdlib deprecation warnings
> Fix stdlib deprecation warnings

- README.md
- manifests/plugin/write_kafka.pp
- spec/classes/collectd_plugin_write_kafka_spec.rb
- templates/plugin/write_kafka.conf.erb
Allow custom Property and Meta.
Custom properties would allow, for example, sasl_ssl configuration to be added to the plugin.
Custom metas would allow specific parameters.
No fix, new feature.
> Plugin write kafka custom properties and meta

- templates/plugin/load.conf.erb
> fixes #901 by excluding the ReportRelative option

- CHANGELOG.md
- metadata.json
> release 11.1.0

- CHANGELOG.md
- metadata.json
> release 11.2.0

- CHANGELOG.md
- metadata.json
> Release 11.4.0

- manifests/plugin/disk.pp
This PR is a bug fix allowing to install the disk package in versions prior CentOS 8 in case `$manage_package` is configured by the user.
> Install disk package if required prior CentOS 8

- Gemfile
> modulesync 2.12.0

- CHANGELOG.md
- metadata.json
> release 12.0.0

- CHANGELOG.md
- metadata.json
> release 12.2.0

- spec/classes/collectd_plugin_python_spec.rb
- spec/defines/collectd_plugin_python_module_spec.rb
- templates/plugin/python/module.conf_config.epp
Reverts voxpupuli/puppet-collectd#965
> Revert "Separation of values for a python plugin array module key"

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- .sync.yml
- Dockerfile
- Gemfile
> modulesync 4.1.0

- templates/plugin/write_graphite/carbon.conf.erb
> Removing extra whitespaces

- metadata.json
- spec/classes/collectd_init_spec.rb
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>
> Add support for EL9

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- .puppet-lint.rc
- Dockerfile
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 5.3.0

- REFERENCE.md
- manifests/plugin/cuda.pp
- manifests/plugin/iscdhcp.pp
- manifests/plugin/snmp_agent.pp
> cleanup puppet-strings documentation

- REFERENCE.md
- manifests/plugin/table/table.pp
> puppet-lint: Fix parameter_order

- manifests/plugin/python/module.pp
Ensure that a python's module config is also removed whenever a python module is not `present`
> Ensure that a python module's config is also removed whenever a python module `ensure` is not `present`

- manifests/plugin/rabbitmq.pp
- metadata.json
> Drop Debian 10 support

- manifests/plugin/rabbitmq.pp
- metadata.json
includes: #1036 #1037 #1038 #1039
> Add Debian 12 support

- manifests/plugin/rabbitmq.pp
- metadata.json
> Drop Ubuntu 18.04 support

- manifests/plugin/rabbitmq.pp
- metadata.json
> Add Ubuntu 22.04 support

- .github/workflows/ci.yml
- .sync.yml
> Run rspec-puppet jobs on CERN runners

- .github/workflows/ci.yml
- .github/workflows/labeler.yml
- .github/workflows/release.yml
- .msync.yml
- .pmtignore
- Gemfile
- manifests/install.pp
- manifests/plugin/python.pp
- manifests/plugin/rabbitmq.pp
- manifests/plugin/write_http.pp
- metadata.json
- spec/classes/collectd_plugin_rabbitmq_spec.rb
- spec/classes/collectd_plugin_write_http_spec.rb
- spec/spec_helper_methods.rb
> modulesync 9.3.0

- Gemfile
- manifests/install.pp
- manifests/plugin/python.pp
- manifests/plugin/rabbitmq.pp
- manifests/plugin/write_http.pp
- metadata.json
- spec/classes/collectd_plugin_rabbitmq_spec.rb
- spec/classes/collectd_plugin_write_http_spec.rb
- spec/spec_helper_methods.rb
> Drop EoL EL7 / CentOS 8 / FreeBSD 12 support

- metadata.json
- spec/classes/collectd_plugin_rabbitmq_spec.rb
> chore: drop EOL Ubuntu 20.04

- CHANGELOG.md
- metadata.json
> Release 15.0.0
