templates/plugin/ntpd.conf.erb

Fixes `Plugin 'ntpd' did not register for value 'IncludeUnitID'.` warnings on Debian.

plugin/ntpd: IncludeUnitID option only available in collectd > 5.2

---

manifests/plugin/perl/plugin.pp

perl -M${module} -e 1 does not work here because of two Problems:
1. $include_dirs is ignored
2. Collectd.pm boundled with collectd uses constants, which are set by the special perl interpreter
build into collectds perl plugin.
Without these constants collectd perl modules will not work.
This commit fixes both issues.

Perl Plugin: changed exec in provider 'false' case:

---

README.md
manifests/params.pp
manifests/plugin/genericjmx.pp
manifests/plugin/genericjmx/connection.pp
manifests/plugin/genericjmx/mbean.pp
manifests/plugin/java.pp
spec/classes/collectd_plugin_genericjmx_spec.rb
spec/classes/collectd_plugin_java_spec.rb
spec/defines/collectd_plugin_genericjmx_connection_spec.rb
spec/defines/collectd_plugin_genericjmx_mbean_spec.rb
templates/plugin/genericjmx.conf.header.erb
templates/plugin/genericjmx/connection.conf.erb
templates/plugin/genericjmx/mbean.conf.erb
templates/plugin/java.conf.erb

There's a new global param, which needs to be updated for the other platforms. I only have centos, fedora, debian, ubuntu, and freebsd available to me (main platform is ubuntu, others would be coming from DO boxes) and as far as I can tell genericjmx isn't available for redhat, and java isn't available at all for freebsd, so I'm not overly certain how that should be handled, if there should be a check in the class to see if it's a supported platform or...
Also, I'd love it if someone who is using the collectd java plugin and knows how it behaves when it comes to multiple `<Plugin "java">LoadPlugin "foo" ...` blocks, like if the JVMArg parameter is global across all java plugins, or just that block, or what. The only one I have a need for at the moment is genericjmx, so I tried to make …

java and genericjmx plugins

---

.travis.yml
manifests/plugin/python.pp

This patch allows the module to be tested on Ruby 1.8.7 but it won't break the build.

Ruby 1.8.7 is deprecated

---

manifests/plugin/python.pp

```
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
* base: ...
* epel: ...
* extras: ...
* updates: ...
Error: No matching Packages to list
```
Feel free to double check:
https://dl.fedoraproject.org/pub/epel/6/x86_64/
https://dl.fedoraproject.org/pub/epel/7/x86_64/c/

Package collectd-python is no longer available in EPEL

---

templates/plugin/write_graphite.conf.erb

LogSendErrors was introduced in 5.4 and earlier versions complain about
'Invalid configration option: LogSendErrors'.

Only set LogSendErrors option if collectd version >= 5.4.

---

manifests/plugin/mysql/database.pp

This change modifies the permissions on the MySQL plugin configuration
file to avoid making it readable by everybody.

Fix permission on the MySQL plugin file

---

.fixtures.yml
CHANGELOG.md
Gemfile.lock
metadata.json
spec/classes/collectd_init_spec.rb
spec/classes/collectd_plugin_disk_spec.rb
spec/classes/collectd_plugin_filecount_spec.rb
spec/classes/collectd_plugin_interface_spec.rb
spec/classes/collectd_plugin_iptables_spec.rb
spec/classes/collectd_plugin_irq_spec.rb
spec/classes/collectd_plugin_tcpconns_spec.rb
spec/classes/collectd_plugin_unixsock_spec.rb

Backwards-incompatible changes:
* Drop Ruby 1.8.7 support
* Package collectd-python is no longer available in EPEL
Features:
* Allow disable forwarding in network::server
Bugs/Maint:
* Fix permission on MySQL plugin file
* Only set LogSendErrors option if collectd version >= 5.4.
* CreateFiles/CreateFilesAsync expect boolean values

Release 3.3.0

---

templates/plugin/python/module.conf.erb

Fix CollectD not being able to start due to an indentation error.
```
Notice: /Stage[main]/Collectd::Plugin::Python/Concat[/etc/collectd.d/python-config.conf]/File[/etc/collectd.d/python-config.conf]/content:
--- /etc/collectd.d/python-config.conf	2015-05-27 10:23:28.631114335 +0200
+++ /tmp/puppet-file20150527-17956-16jo2pd	2015-05-27 10:26:21.561630822 +0200
@@ -6,5 +6,6 @@
Import "puppet_reports"
<Module "puppet_reports">
-      ReportsDir "/var/lib/puppet/reports"
-    </Module></Plugin>
+      ReportsDir "/var/lib/puppet/reports"
+  </Module>
+</Plugin>
```

Fix CollectD not being able to start due to an indentation error.

---

manifests/plugin/snmp/host.pp

I get errors when running "bundle exec rake spec SPEC_OPTS='--format documentation'". validate_re can only operate on strings.
collectd::plugin::snmp::host
default params
should contain File[snmp-host-foo.example.com.conf] with ensure => "present" and path => "/etc/collectd/conf.d/25-snmp-host-foo.example.com.conf" (FAILED - 1)
should contain File[snmp-host-foo.example.com.conf] that notifies Service[collectd] (FAILED - 2)
should contain File[snmp-host-foo.example.com.conf] with content =~ /<Plugin snmp>/ (FAILED - 3)
should contain File[snmp-host-foo.example.com.conf] with content =~ /<Host "foo\.example\.com">/ (FAILED - 4)
should contain File[snmp-host-foo.example.com.conf] with content =~ /Address "foo\.example\.com"/ (FAILED - 5)
should contain File[snmp-host-foo.example.com.conf] …

snpm/host.pp validate_re validate on string

---

tests/plugins/tail.pp

running bundle rake validate fails with following errors:
bundle exec rake validate
ruby -c lib/facter/collectd_version.rb
Syntax OK
---> syntax:manifests
Use of reserved word: type, must be quoted if intended to be a String value at /home/piotr/git/puppet-module-collectd/tests/plugins/tail.pp:10:7
Use of reserved word: type, must be quoted if intended to be a String value at /home/piotr/git/puppet-module-collectd/tests/plugins/tail.pp:16:7
Use of reserved word: type, must be quoted if intended to be a String value at /home/piotr/git/puppet-module-collectd/tests/plugins/tail.pp:29:7
Found 3 errors. Giving up
rake aborted!
Quoting type (and all other keys to be style consistent) makes rake validate work

quote reserved word type in tail.pp so rake validate succeeds

---

templates/plugin/cpu.conf.erb

The current cpu plugin breaks older collectd versions as they fail to parse the <Plugin> ...</Plugin> stuff.

fix cpu config parsing

---

templates/plugin/python/module.conf.erb

Fix for: https://github.com/pdxcat/puppet-module-collectd/issues/281

Fix formatting in python plugin template

---

manifests/plugin/curl_json.pp
metadata.json

I need multiple curl_json instances which is generated automaticly. 
Use of ensure_packages() allow to call collectd::plugin::curl_json more than once.

fix multiple instances for curl_json

---

manifests/plugin/write_graphite.pp

Hello:
This allows default values to be passed in for carbon blocks, and it is useful in the event that you have many unique carbon backends.
Critique welcome.
Inspiration taken from https://github.com/jfryman/puppet-nginx/blob/master/manifests/init.pp#L300

Add carbon default values as parameter to create_resources

---

manifests/plugin/iptables.pp

Needed on centos 6 for example, where the package does not exist at all.

add option to not install collectd-iptables package

---

spec/classes/collectd_plugin_iptables_spec.rb
templates/plugin/iptables.conf.erb

When using the iptables plugin, this allows you to provide more than one chain for each table by passing an array as the hash value. For example:
```puppet
class { 'collectd::plugin::iptables':
chains  => {
'filter' => ['INPUT','OUTPUT'],
},
}
```

Allow iptables chains parameter to be an array (fix #237)

---

.travis.yml
CHANGELOG.md
Gemfile
Gemfile.lock
Rakefile
metadata.json

This module now lives on the puppet community github organization.
New features:
* Add option to not install collectd-iptables on centos 6
* Allow iptables chains parameter to be an array
* Support UdevNameAttr attribute on disk plugin (fixes #300)

Release 4.1.0

---

README.md

I had troubles using python manifest today and it took me a while to notice the problem. This should fix it for other users.

Typo: changed colon to =>, since colon generates error

---

README.md

I noticed this is missing in README file.

Exec plugin can also be used with a parameterized class.

---

manifests/plugin/tcpconns.pp
spec/classes/collectd_plugin_tcpconns_spec.rb
templates/plugin/tcpconns.conf.erb

Add support for the allportssummary option added to the tcpconns module introduced in version collectd-5.5.0.

Add support for the new AllPortsSummary option.

---

manifests/plugin/snmp/data.pp
templates/plugin/snmp.conf.erb
templates/plugin/snmp/data.conf.erb

Added support for InstancePrefix, Scale and Shift options, both when using the parametized class and the defined type.
Also it's removed the sorting of Values passed to parametized class, because you can feed the wrong values to the type defined in types.db (in fact, they are not sorted when using the defined type).
Finally, check whether the option Table is set when using the parametized class

Enhance and fix snmp plugin

---

templates/plugin/snmp.conf.erb

Fix a minor typo in the snmp.conf.erb template.

SNMP template typo fix s/Shitf/Shift/

---

README.md
manifests/plugin/filter.pp
manifests/plugin/filter/chain.pp
manifests/plugin/filter/match.pp
manifests/plugin/filter/rule.pp
manifests/plugin/filter/target.pp
spec/classes/collectd_plugin_filter_spec.rb
spec/defines/collectd_plugin_filter_chain_spec.rb
spec/defines/collectd_plugin_filter_match_spec.rb
spec/defines/collectd_plugin_filter_rule_spec.rb
spec/defines/collectd_plugin_filter_target_spec.rb
templates/plugin/filter/match.erb
templates/plugin/filter/target.erb

The Chain plugin is nice, but i was missing some flexibility. 
This is a new plugin which manages the creation of the whole filter configuration. Its splitted to multiple resources to create a whole chain: chain, rule, match, target.

Add Plugin Filter

---

Gemfile.lock
manifests/init.pp
manifests/params.pp

Hauskeeping! This commit removes a duplicate $version paramter. It
also moves the $minimum_version default to the params class and
aligns an inline comment.

Fixing duplicate param and some housekeeping

---

manifests/config.pp
manifests/init.pp
templates/collectd.conf.erb

the template shouldn't use collectd_real_version
actually, nothing should use collectd_real_version.
collectd_version is there to normalize a potentially empty value.

use the correct collectd_version in templates

---

.sync.yml

once we decide that this is useful to the general public we should just
make sure it ends up in spec_helper

modulesync integration: spec_helper unmanaged for now

---

manifests/init.pp
manifests/install.pp
manifests/params.pp
manifests/plugin/amqp.pp
manifests/plugin/apache.pp
manifests/plugin/bind.pp
manifests/plugin/curl.pp
manifests/plugin/iptables.pp
manifests/plugin/libvirt.pp
manifests/plugin/lvm.pp
manifests/plugin/mysql.pp
manifests/plugin/netlink.pp
manifests/plugin/nginx.pp
manifests/plugin/perl.pp
manifests/plugin/perl/plugin.pp
manifests/plugin/ping.pp
manifests/plugin/postgresql.pp
manifests/plugin/rrdtool.pp
manifests/plugin/sensors.pp
manifests/plugin/snmp.pp
manifests/plugin/varnish.pp
manifests/plugin/write_riemann.pp
manifests/plugin/write_sensu.pp
spec/classes/collectd_init_spec.rb

Sometimes installing packages is done in a different way (eg. epel may
not be enabled by default)
The dependencies still hold.

Make the management of the collectd package optional

---

manifests/params.pp

With the current name I get:
```sh
root@host:~# /usr/sbin/svcadm enable -s collectd
svcadm: Pattern 'collectd' doesn't match any instances
```
The current settings are equivalent to dropping a directory named 'conf.d' into
'/etc' which makes in nonobvious to which package it belongs.

Solaris variables

---

spec/classes/collectd_plugin_filecount_spec.rb
templates/plugin/filecount.conf.erb

Our collectd 4.1 chokes on an empty Plugin block.
This can happen when not using the `directories` parameter to
collectd::plugin::filecount and instead using only
collectd::plugin::filecount::directory .

[filecount] do not an emit empty <Plugin> block

---

lib/facter/collectd_real_version.rb

ruby 1.8.7 does noet support regex group naming

removed group naming from regex for compatibility with ruby 1.8.7

---

manifests/plugin/dbi/database.pp

Right now, this pseudo Puppet-code:
::collectd::plugin::dbi::query { 'test': ... }
::collectd::plugin::dbi::database { 'test':
driver => 'mysql',
driveroption => {
'host' => 'localhost',
'mysql_unix_socket' => ...,
'username' => ...,
'password' => ...,
'dbname' => ...,
},
query => [ 'test' ],
}
produces these configuration blocks:
<Plugin dbi>
<Query test>
...
</Query>
<Database "">       <-----
...
</Database>
</Plugin>
The database-name references a non-existent @databasename variable, so introduce
this variable, as it is also introduced and used inside
::collectd::postgresql::database, so that the expected output is produced:
<Plugin dbi>
<Query test>
...
</Query>
<Database "test">   <-----
...
</Database>
</Plugin>

Fix empty Database-names in dbi-plugin

---

README.md
manifests/config.pp
manifests/init.pp
manifests/params.pp
manifests/typesdb.pp
spec/classes/collectd_init_spec.rb
spec/defines/collectd_typesdb_spec.rb

Other software (InfluxDB) can be configured to read from the Collectd types database, this will allow someone to set a different file mode on both the collectd.d directory and any typesdb files this module creates. It's probably safer than changing the default file mode of File[collectd.d], I don't know if plugins store passwords in there.

Allow changing of the file mode of the collectd plugin directory and custom typesdb files

---

spec/defines/collectd_plugin_python_module_spec.rb
templates/plugin/python/module.conf.erb

This makes the module.conf.erb template support complex config, i.e. config
with values that are arrays or hashes.
Closes #390

Make module.conf.erb support complex config

---

README.md

Rest of the document uses bullets rather than headings

Fixes mongodb plugin params docs to be consistent

---

manifests/plugin/python.pp

Change-Id: I2dc6239228fc19da1bcfa426f75388529b9b3eae
In addition to https://github.com/voxpupuli/puppet-collectd/pull/393, last parameter that should be renamed in python plugin.

Fixing bug with rename collectd::params::package variable

---

templates/mysql-database.conf.erb

The InnodbStats option of the mysql plugin was introduced in collectd 5.5.

collectd < 5.5 doesn't come with mysql InnodbStats.

---

.fixtures.yml
manifests/plugin/dbi/database.pp
manifests/plugin/dbi/query.pp
manifests/plugin/exec/cmd.pp
manifests/plugin/postgresql/database.pp
manifests/plugin/postgresql/query.pp
manifests/plugin/postgresql/writer.pp
manifests/plugin/processes.pp
manifests/plugin/processes/process.pp
manifests/plugin/processes/processmatch.pp
manifests/plugin/python/module.pp
manifests/plugin/write_graphite/carbon.pp
spec/defines/collectd_typesdb_spec.rb

* Bumps fixture versions of concat to 2.1.0
* Fixes two tests
* Removes $ensure from concat::fragment as this is no longer support in concat 2.x

Add support for puppetlabs-concat 2.x

---

README.md

fix collectd::plugin::write_sensu parameter names to refer to sensu instead of riemann

fix typo in write_sensu class example

---

spec/classes/collectd_plugin_curl_spec.rb
spec/classes/collectd_plugin_iptables_spec.rb
spec/classes/collectd_plugin_libvirt_spec.rb
spec/classes/collectd_plugin_ping_spec.rb
spec/classes/collectd_plugin_postgresql_spec.rb
spec/classes/collectd_plugin_snmp_spec.rb
spec/classes/collectd_plugin_varnish_spec.rb
spec/defines/collectd_plugin_curl_page_spec.rb
spec/defines/collectd_plugin_mysql_database_spec.rb

`Undefined variable "collectd::manage_package"; class collectd has not been evaluated at /home/travis/build/voxpupuli/puppet-collectd/spec/fixtures/modules/collectd/manifests/plugin/mysql.pp:5 on node testing-worker-linux-docker-d88cd221-3376-linux-15.prod.travis-ci.org`

Fixes issue with strict variables

---

manifests/plugin/python.pp

plugin_conf_dir has to be present prior to creation of python_conf.
Fixes #416

Ensure plugin_conf_dir to be present

---

manifests/plugin/load.pp
spec/classes/collectd_plugin_load_spec.rb
templates/loadplugin.conf.erb

From CollectD docs:
```
ReportRelative false|true
When enabled, system load divided by number of available CPU cores is reported for intervals 1 min, 5 min and 15 min. Defaults to false.
```
- https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_load

Adds report_relative parameter

---

manifests/plugin/apache/instance.pp
spec/defines/collectd_plugin_apache_instance_spec.rb
templates/plugin/apache/instance.conf.erb

This PR adds a new defined type `collectd::plugin::apache::instance` that allows to automatize the configuration of apache monitoring in a central collectd server:
Consider the following use case:
Let's define the `profile::apache` class as: 
```
class profile::apache {
...
class { '::apache' :
...
}
@@collectd::plugin::apache::instance { $hostname :
...
}
}
```
and the `profile::collectd::server` class as:
```
class profile::collectd::server {
...
Collectd::Plugin::Apache::Instance <<||>>
}
```
Whenever you apply the `profile::apache` class to a node, all the monitoring configuration of the apache instance will be 'automagically' generated on the central collectd server.

split out apache instance into define

---

.rubocop.yml
.travis.yml
CONTRIBUTING.md
Gemfile
spec/classes/coverage_spec.rb

See https://github.com/voxpupuli/modulesync_config/pull/93
This commit updates the module to our latest modulesync configuration.

Pin rake to avoid rubocop/rake 11 incompatibility

---

manifests/plugin/load.pp
templates/loadplugin.conf.erb
templates/plugin/load.conf.erb

In reference to: https://github.com/voxpupuli/puppet-collectd/commit/783c128fc2ff614e2b298c94d7c4c7702f3206ce#diff-71752fe3834a3d780fea4260c2cc003e
it looks like templates/loadplugin.conf.erb was confused for templates/plugin/load.conf.erb -- the former being used to build parameterized conf files from manifests/plugin/* , and the latter where .load files for specific manifests are built to include in the conf file.
The outcome was that ReportRelative was being dropped in the declaration of the plugin, rather than in the plugin's configuration.
the change in the manifest from undef to false supports default behavior.
--- 
Remove Load-Plugin specific lookup from loadplugin.conf.erb now that Load-Plugin's manifest uses template/plugin/load.conf.erb correctly
equals signs not standard

have configurable load plugin use template standard

---

lib/facter/collectd_version.rb
spec/unit/collectd_real_version_spec.rb

Fixes #421 - ```collectd_real_version``` in ```init.pp``` not set correctly as the fact returns ```nil```, and ```pick``` will accept that as a value.

Set collectd_version fact to empty string if collectd not installed

---

manifests/plugin/statsd.pp
templates/plugin/statsd.conf.erb

As is, this is a backwards incompatible change. Is there a way either in the manifest or the template to check if the value is an array or scalar first?

TimerPercentile can be specified multiple times

---

manifests/init.pp
manifests/params.pp
manifests/service.pp
spec/classes/collectd_init_spec.rb

Added a parameter to toggle automatic starting of the collectd service.  
The default behavior is the same as before, which is to automatically start the service.

add manage_service param

---

templates/plugin/python/module.conf.erb

Require 'shellwords' in the template. Fixes #456

---

README.md
manifests/plugin/rabbitmq.pp
spec/classes/collectd_plugin_rabbitmq_spec.rb

This is picking up where https://github.com/voxpupuli/puppet-collectd/pull/478 left off. I have reduced the changes in this to just what is needed to fix my busted stuff for the rabbitmq python module check.
I'm having problems getting the rake tasks to run due to a gem issue. Curious if this is occurring upstream as well.
```
An error occurred while installing listen (3.1.3), and Bundler cannot continue.
Make sure that `gem install listen -v '3.1.3'` succeeds before bundling.
```
The tests were passing previously in #478 so I believe this will pass

Fix rabbitmq module

---

README.md
manifests/plugin/write_riemann.pp
spec/classes/collectd_plugin_write_riemann_spec.rb
templates/plugin/write_riemann.conf.erb

This has been tested in a real environment. Unit tests are also provided.
I'm a bit on the fence about calling the parameter `tags`, due to possible confusion with the Puppet metaparameter `tag`, but tried to follow existing conventions from this and other plugin manifests.

Adds the ability to set tags and attributes for the `write_riemann` plugin

---

manifests/plugin/curl_json.pp
templates/plugin/snmp.conf.erb

The SNMP plugin allows Instance to be undefined if Table is set to true.
This is documented on https://collectd.org/documentation/manpages/collectd-snmp.5.shtml
"If Table is set to true and Instance is omitted, then "SUBID" will be used as the instance."

SNMP Plugin - Instance should be optional

---

templates/tail-file.conf.erb

ExcludeRegex was set in config file even if it wasn't defined. This fix only sets ExcludeRegex when you define it in manifest.

Only set ExcludeRegex in config file if variable is defined

---

README.md
templates/curl_json.conf.erb

When declaring statsd plugin, timerpercentile must be an array.
There is also a cosmetic fix in curl_json template which removes a bunch of blank lines.

Documentation fix and removed blank lines from curl_json

---

manifests/config.pp

$has_wordexp was always being considered to be false as it is not being called from the collectd main class (which in turns calls it from the params class). This bug should now be fixed.

Adding has_wordexp variable for template

---

spec/defines/collectd_plugin_apache_instance_spec.rb
templates/plugin/apache.conf.erb
templates/plugin/apache/instance.conf.erb

Currently the plugin fails to load when passing `verifypeer` and `verifyhost` args to an instance definition:
`cf_util_get_boolean: The VerifyPeer option requires exactly one boolean argument.`

Apache plugin - Remove quotes from VerifyPeer and VerifyHost

---

manifests/plugin/filter.pp
templates/plugin/filter/target.erb

Also needed to add Float as supported value in plugin/filter/target.erb template.
Scale is usefull for scaling memory size from bytes to GB.
This now works (tested on our environment):
$chain2name = 'PreCache'
collectd::plugin::filter::chain { $chain2name:
}
$rule2name = 'scale_to_gb'
collectd::plugin::filter::rule { $rule2name:
chain => $chain2name,
}
collectd::plugin::filter::match { "regex_mem":
chain   => $chain2name,
rule    => $rule2name,
plugin  => 'regex',
options => {
'Type' => '^(memory|swap)$'
}
}
collectd::plugin::filter::target{ "scale_mem":
chain   => $chain2name,
rule    => $rule2name,
plugin  => 'scale',
options => {
'Factor' => 0.000000000931322574615478515625,
}
}

Added scale plugin

---

manifests/plugin/disk.pp
spec/classes/collectd_plugin_disk_spec.rb

If $manage_package is false, the else block will be used instead disable managing the package.

Check $manage_package if not undef

---

templates/plugin/filter/target.erb

This change allows having several occurrences of PluginInstance within the same target filter definition block.
```
collectd::plugin::filter::target{ "overwrite OIDs":
chain   => $chainname,
rule    => $rulename,
plugin  => 'replace',
options => {
'PluginInstance' => ['"string1." "replace_string_1_"','"string2-" "replace_string_2"','"\"" "."']
}
```
Resulting in this output in config file
```
<Target "replace">
PluginInstance "string1." "replace_string_1_"
PluginInstance "string2-" "replace_string_2_"
PluginInstance "\"" "."
</Target>
```

target replace filter fix to allow identical keys with different values

---

manifests/plugin/disk.pp

Please check the following items before submitting a PR -- thank you!
Note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).
closed once this PR gets merged, i.e: `Closes #1554` in the body of a commit
tries to address multiple issues. Though we prefer one PR per feature/fix,
sometimes that's not feasible. In that case ensure that a single feature/fix
and associated tests and documentation is bundled up in one commit
Optional, but extra points:
reintroduced
- - -
if we set $manage_package it doesn't do what is expected. We must instead check if it's undefined as the default is to undefined.

Fix logic problem

---

manifests/plugin/write_kafka.pp

This should fix #539
added kafka_hosts param which allows usage of hosts-array
kafka_host is still valid and will be merged correctly
default (if nothing else given) will still be localhost

plugin/write_kafka.pp:

---

manifests/config.pp
spec/classes/collectd_plugin_dbi_spec.rb
spec/classes/collectd_plugin_disk_spec.rb
spec/classes/collectd_plugin_exec_spec.rb
spec/classes/collectd_plugin_genericjmx_spec.rb
spec/classes/collectd_plugin_postgresql_spec.rb
spec/classes/collectd_plugin_processes_spec.rb
spec/classes/collectd_plugin_python_spec.rb
spec/classes/collectd_plugin_write_graphite_spec.rb
spec/defines/collectd_plugin_filter_chain_spec.rb

`Concat` types create a lockfile in the directory where the file will end up. Sometimes the `concat` will run before the `File['/etc/collectd.d']` resource. I added ordering to ensure that all `concat`s will occur after the folder is created.
Here is an example of the error:
```
$ puppet agent -t
...
Error: Could not set 'file' on ensure: No such file or directory - /etc/collectd.d/processes-config.conf20160706-24270-1k3tm2o.lock
Error: Could not set 'file' on ensure: No such file or directory - /etc/collectd.d/processes-config.conf20160706-24270-1k3tm2o.lock
Wrapped exception:
No such file or directory - /etc/collectd.d/processes-config.conf20160706-24270-1k3tm2o.lock
Error: /Stage[main]/Collectd::Plugin::Processes/Concat[/etc/collectd.d/processes-config.conf]/File[/etc/collectd.d/process …
```

Fix for Concat lockfile issue

---

manifests/plugin/write_graphite.pp
spec/classes/collectd_plugin_write_graphite_spec.rb

Ensures that `/etc/collectd/conf.d/write_graphite-config.conf` can be set to `absent` without failing on a puppet run.
This is neccessary for encrypted communication to the graphite server.
See #533

remove write_graphite-config.conf on absent (fixes #533)

---

README.md
manifests/plugin/cpu.pp
spec/classes/collectd_plugin_cpu_spec.rb
templates/plugin/cpu.conf.erb

As title says, this PR adds support for ReportNumCpu. From collectd site: When set to true, reports the number of available CPUs.

Add support for ReportNumCpu in CPU plugin introduced in collectd 5.6

---

lib/facter/python_dir.rb
spec/unit/python_dir_spec.rb

Avoids issue with variable undefined. Previous behavior resolved to 'nil', causing;
Error: Evaluation Error: Unknown variable: '::python_dir'.

Fallback to empty string if Python is not installed

---

README.md
manifests/init.pp
manifests/install.pp
manifests/params.pp
manifests/repo.pp
manifests/repo/debian.pp
manifests/repo/redhat.pp
spec/classes/collectd_init_spec.rb
spec/default_module_facts.yml

* Allows installation of 5.6 version of Collectd or master release (potential 5.7)
* Refactor repo management behaviour into it's own classes
* Add parameter to specify version from bleeding edge repos from CI
Closes https://github.com/voxpupuli/puppet-collectd/issues/578

Adds Collectd CI Package repos

---

lib/facter/python_dir.rb
spec/unit/python_dir_spec.rb

Use the correct method (value) for retrieving osfamily fact.
Add test for RedHat to confirm conditional is working correctly.

Fix python_dir fact for RedHat.

---

README.md

Commit c0faa91ffdd7ffdd6d0bc815e001fddb340dd21e has renamed `type` => `agg_type`. Fixing README.md

Fix documentation for aggregation type parameter

---

manifests/config.pp

Tag collectd's concat resources

---

.fixtures.yml
metadata.json

this version is puppet 4 only and doesn't work with this module since it
still supports Puppet 3. Also updated the .fixture.yml to get the
correct version for rspec tests

pin puppet-yum to < 1.0.0

---

.rubocop.yml
manifests/plugin/genericjmx/connection.pp
spec/defines/collectd_plugin_genericjmx_connection_spec.rb
templates/plugin/genericjmx/connection.conf.erb

This should not be the default, it doesn't make sense for localhost
bound JMX connections.

Stop specifying $name as the default host value

---

README.md
manifests/plugin/python.pp
spec/classes/collectd_plugin_python_spec.rb

It would very helpful for us to have a custom parameter to put a custom location of the python module configuration.

Parametrize destination of python config

---

manifests/plugin/statsd.pp
spec/classes/collectd_plugin_statsd_spec.rb
templates/plugin/statsd.conf.erb

Collectd has add a 'CounterSum' configration which is not currently supported by
puppetd-collected. More information on:
* Current config options: https://github.com/collectd/collectd/blob/master/src/collectd.conf.pod#plugin-statsd
* PR introducing CounterSum: https://github.com/collectd/collectd/pull/1363
* Commit adding CounterSum: https://github.com/octo/collectd/commit/eaf8c7a28723dc81fc035e3a15a0ca1dbb46090c
This PR adds support for CounterSum and a basic spec for statsd, which was
previously missing.

Add CounterSum support to statsd config

---

templates/plugin/network.conf.erb
templates/plugin/openldap.conf.erb
templates/plugin/sensors.conf.erb
templates/plugin/write_http.conf.erb

Fixes the #639 issue (broken quoted boolean handling by newer collectd versions)

Remove quotes from boolean options

---

manifests/plugin/oracle.pp
manifests/plugin/oracle/database.pp
manifests/plugin/oracle/query.pp
spec/classes/collectd_plugin_oracle_spec.rb
spec/defines/collectd_plugin_oracle_database_spec.rb
spec/defines/collectd_plugin_oracle_query_spec.rb
templates/plugin/oracle/database.conf.erb
templates/plugin/oracle/query.conf.erb

Added plugin oracle

---

README.md
manifests/plugin/cuda.pp
spec/classes/collectd_plugin_cuda_spec.rb

Added cuda GPU plugin

---

.fixtures.yml
manifests/plugin/cuda.pp
manifests/plugin/rabbitmq.pp
manifests/repo.pp
manifests/repo/redhat.pp
metadata.json
spec/classes/collectd_init_spec.rb
spec/spec_helper_acceptance.rb

Installing the RPM is clunky and 99% of people use the EPEL module

Changes RedHat repo to use the EPEL module

---

manifests/type.pp
spec/defines/collectd_type_spec.rb

Hi,
this pr implement #549 in a **dirty** way. It should be refactor if puppet 3 is dropped. (https://github.com/voxpupuli/plumbing/issues/21 hopefully gets voted in the near feature... )
If you reject this because inline_template is not the state of the art I rewrite it to own defines for every type definition.

Fixes #549: Unable to define a multi-value type

---

manifests/plugin/oracle/database.pp
spec/defines/collectd_plugin_oracle_database_spec.rb

Hi,
today, we test the module against a real oracle database and we figure out, the database configuration must be at the bottom.

Oracle Database definition must be at bottom

---

manifests/plugin/curl_json.pp
spec/acceptance/curl_json_spec.rb
spec/acceptance/nodesets/docker/ubuntu-12.04.yml
spec/defines/collectd_plugin_curl_json_spec.rb
spec/spec_helper_acceptance.rb

* Ubuntu 12.04 uses "libyajl1", others use "libyajl2"
* Adds spec for which package is present
* Also adds acceptance tests for differences
Rebase of https://github.com/voxpupuli/puppet-collectd/pull/626 with tests 👍

Add Support for older versions of `libyajl`

---

manifests/params.pp

this is only available on debian/redhat osfamily. So we should only
enable it on these platforms, not on all.

provide sane defaults for manage_repo

---

manifests/init.pp
manifests/plugin/curl/page.pp
manifests/plugin/java.pp
spec/defines/collectd_plugin_curl_page_spec.rb
templates/plugin/curl-page.conf.erb

according this documentation page https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_curl
we can start collecting response code

add $measureresponsecode for curl plugin

---

README.md

The module definitions now need arrays for configurations. README was updated to show that for defining multiple modules, but the single-module definition was forgotten.

Update `collectd::plugin::python::module` README

---

spec/classes/collectd_plugin_amqp_spec.rb
spec/unit/python_dir_spec.rb
templates/plugin/amqp.conf.erb

I wrote some tests and caught a bug, it seems.
Not much to say other than that. These tests aren't complete, but they're something.

Add tests for the AMQP plugin and fix broken StoreRates configuration when amqpformat = JSON

---

manifests/params.pp
manifests/plugin/amqp.pp
manifests/plugin/bind.pp
manifests/plugin/curl.pp
manifests/plugin/curl_json.pp
manifests/plugin/dbi.pp
manifests/plugin/genericjmx.pp
manifests/plugin/ipmi.pp
manifests/plugin/iptables.pp
manifests/plugin/java.pp
manifests/plugin/lvm.pp
manifests/plugin/mysql.pp
manifests/plugin/netlink.pp
manifests/plugin/nginx.pp
manifests/plugin/perl.pp
manifests/plugin/ping.pp
manifests/plugin/postgresql.pp
manifests/plugin/rrdcached.pp
manifests/plugin/sensors.pp
manifests/plugin/snmp.pp
manifests/plugin/varnish.pp
manifests/plugin/write_riemann.pp
manifests/plugin/write_sensu.pp
spec/classes/collectd_plugin_cgroups_spec.rb
spec/classes/collectd_plugin_logfile_spec.rb
spec/classes/collectd_plugin_memory_spec.rb
spec/classes/collectd_plugin_swap_spec.rb
spec/defines/collectd_plugin_network_listener_spec.rb
spec/defines/collectd_plugin_network_server_spec.rb

I was tracking down why we had forked our own copy of this module and found one of the changes was simply changing the case of `Redhat` to `RedHat` in some common places. Before I remembered that Puppet helpfully compares strings case insensitively I updated all occurrences given the module uses both forms throughout. Should Puppet ever change its behaviour the latter form matches exactly what facter returns.
To keep my employers legal team happy, I have to include the following:
> This contribution is provided 'as is' and without any warranty or guarantee of any kind, express or implied, including in relation to its quality, suitability for a particular purpose or non-infringement. To the extent permitted by law, in no event shall the creator of this contribution be liable for any claim, …

Change 'Redhat' to 'RedHat' when comparing against the osfamily fact

---

.fixtures.yml
.gitignore
.msync.yml
.rspec_parallel
.rubocop.yml
Gemfile
spec/acceptance/nodesets/archlinux-2-x64.yml
spec/default_module_facts.yml
spec/spec_helper_methods.rb

Modulesync 0.21.3

---

metadata.json

4.6.1 was recommended while we did our upgrade from puppet3 to puppet4.
However: There were some bugs in 4.6 and puppetlabs made 4.7.0 the new
recommended and LTS version.

Bump required puppet version 4.6.1->4.7.0

---

metadata.json

we should not support outdated operating systems. They all went EOL in
the past months. This also reduces our test-runtime significatly.

drop legacy OS from support matrix

---

manifests/plugin/redis.pp
templates/plugin/redis.conf.erb
types/redis/node.pp

I found the `collectd-redis` sub-package wasn't being installed when I included the plugin so I added the logic based on some of the other plugins. I also refactored the code to use Puppet 4 data types and tidied up the template slightly.
To keep my employers legal team happy, I have to include the following:
> This contribution is provided 'as is' and without any warranty or guarantee of any kind, express or implied, including in relation to its quality, suitability for a particular purpose or non-infringement. To the extent permitted by law, in no event shall the creator of this contribution be liable for any claim, damage or other liability, whether arising in contract, tort or otherwise, arising out of or in connection with this contribution.

Install Redis plugin package if needed

---

manifests/plugin/write_graphite.pp
manifests/plugin/write_http.pp
manifests/plugin/write_kafka.pp
manifests/plugin/write_log.pp
manifests/plugin/write_riemann.pp
manifests/plugin/write_sensu.pp

Hello, to my knowledge it makes no sense to configure interval for write plugins. Collectd has no concept of interval for write plugins and if configured, it is silently ignored. It is therefore better to remove it from the configuration so that manifests don't give a false impression that this parameter does something useful.

Remove interval parameter from write plugins.

---

README.md
manifests/plugin/snmp.pp
manifests/plugin/snmp/data.pp
manifests/plugin/snmp/host.pp
spec/classes/collectd_plugin_snmp_spec.rb
spec/defines/collectd_plugin_snmp_data_spec.rb
spec/defines/collectd_plugin_snmp_host_spec.rb
templates/plugin/snmp.conf.erb
templates/plugin/snmp/data.conf.erb
templates/plugin/snmp/host.conf.erb
types/snmp/authprotocol.pp
types/snmp/data.pp
types/snmp/host.pp
types/snmp/host/v2.pp
types/snmp/host/v3.pp
types/snmp/privacyprotocol.pp
types/snmp/securitylevel.pp
types/snmp/version.pp
types/snmp/version/v2.pp
types/snmp/version/v3.pp

This PR adds SNMPv3 support to the SNMP plugin which should fix #236, I also took the opportunity to refactor the plugin to use Puppet 4.x data types.
The only breaking change AFAICT is that I renamed the `invertmatch` and `instanceprefix` parameters to `invert_match` and `instance_prefix` respectively in the `collectd::plugin::snmp::data` defined type to match the hash keys passed in the `data` parameter in `collectd::plugin::snmp` class given everything else matched up.
To keep my employers legal team happy, I have to include the following:
>This contribution is provided 'as is' and without any warranty or guarantee of any kind, express or implied, including in relation to its quality, suitability for a particular purpose or non-infringement. To the extent permitted by law, in no event …

Add SNMPv3 support

---

README.md
examples/plugins/iptables.pp
manifests/plugin/iptables.pp
spec/classes/collectd_plugin_iptables_spec.rb
templates/plugin/iptables.conf.erb

This PR is related to issue #693 and adds support for the `Chain6` configuration directive of the `iptables` Collectd plugin.
Closes GH-693

Add support for Chain6 directive

---

README.md
manifests/plugin/zookeeper.pp
spec/classes/collectd_plugin_zookeeper_spec.rb
templates/plugin/zookeeper.conf.erb

Add Zookeeper plugin

---

manifests/plugin/python.pp

When the package installation check in `manifests/plugin/python.pp` changed from all RedHat distress to Fedora the module stopped working on Amazon Linux. This change updates the check to install the module on Amazon Linux.

Install 'collectd-python' package on Amazon Linux.

---

metadata.json

Bump up the puppetlabs-stdlib version so that the Stdlib::Httpurl data type can be used

Bump puppetlabs-stdlib to 4.13.1

---

manifests/plugin/apache/instance.pp
metadata.json

- Use data types for the Apache plugin
- Bump up the puppetlabs-stdlib version so that Stdlib::Httpurl can be
used

plugin::apache - Use data types

---

manifests/init.pp
manifests/params.pp

An alternative to https://github.com/voxpupuli/puppet-collectd/pull/707

Fix strict variables error when facts are missing

---

manifests/plugin/filecount/directory.pp

- Add more data types
- $path is a required parameter, not optional
- Also be explict with $collectd::plugin_conf_dir reference

plugin::filecount::directory - data type changes

---

manifests/plugin/exec/cmd.pp

- Add data types for user and group
- Remove $ensure as it is currently unused
- Remove long deprecated handling of old file path

collectd::plugin::exec::cmd clean up

---

manifests/plugin/apache/instance.pp

Don't assign $conf_dir and $root_group from variables in params.pp directly

plugin::apache::instance -don't assign from params

---

manifests/plugin/genericjmx/connection.pp
spec/defines/collectd_plugin_genericjmx_connection_spec.rb
templates/plugin/genericjmx/connection.conf.erb

- Breaking change: $collect now only accepts an array, not either an array or string

plugin::genericjmx::connection - Use data types

---

README.md
manifests/plugin/genericjmx/mbean.pp
spec/defines/collectd_plugin_genericjmx_mbean_spec.rb
templates/plugin/genericjmx/mbean.conf.erb

- Breaking change: $instance_from can now only be an array, not array or string

plugin::genericjmx::mbean - Use data types

---

manifests/plugin/filter/target.pp
types/filter/builtintarget.pp
types/filter/plugintarget.pp
types/filter/target.pp

plugin::filter::target - Use data types

---

templates/plugin/postgresql/query.conf.erb

Sometimes needs make query without parameters, for example check lags on slaves:
"SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()))::INT"

added: check params variable in query pg template

---

manifests/plugin/processes.pp

This fixes a old silent bug that was created by
395036ae332c56800481459fef9f1691a484de9f
This commit makes it possible define single process again like:
collectd::plugin::processes::process { 'collectd' : }
Without also having to create:
class { 'collectd::plugin::processes':
processes => [ 'foo', 'bar' }
This fixes the issues #652 and #595.

Make it possible to add processes one by one

---

spec/classes/collectd_plugin_fscache_spec.rb
spec/defines/collectd_plugin_curl_json_spec.rb
templates/curl_json.conf.erb

*If* in the 'post' parameter we've been given a valid json string, it
definately won't work unless we do some escaping of double quotes.
If any strings in the JSON also contain (correctly escaped) double
quotes, even more backslashes are needed.
eg. The following JSON
```
{"param1":"something with a double quote \" in it"}
```
Would end up in the config file as
```
Post "{\"param1\":\"something with a double quote \\\" in it\"}"
```

Escape json posts in curl_json plugin

---

manifests/plugin/ovs_stats.pp
spec/classes/collectd_plugin_ovs_stats_spec.rb
templates/plugin/ovs_stats.conf.erb

This patch is adding support for ovs_stats plugin configuration and installation.

Adds class ovs_stats plugin

---

spec/defines/collectd_plugin_mysql_database_spec.rb
templates/mysql-database.conf.erb

This fixes voxpupuli/puppet-collectd#757 by correcting both the parameter name and the variable name in `templates/mysql-database.conf.erb`.

Fix the MySQL plugin's WsrepStats parameter

---

manifests/plugin/ovs_events.pp
spec/classes/collectd_plugin_ovs_events_spec.rb
templates/plugin/ovs_events.conf.erb

This patch is adding support for ovs_events plugin configuration and installation.

Adds class ovs_events plugin

---

README.md
manifests/init.pp
manifests/params.pp
manifests/repo/debian.pp
spec/classes/collectd_init_spec.rb

We have noticed sometimes puppet fails to provision our servers due to failing connectivity to pgp.mit.edu.
This MR allows you to choose the keyserver in case such an event happens.
Thanks to [Erasys GmbH](https://www.erasys.de/)

feat: add package_keyserver parameter

---

README.md
manifests/plugin/intel_pmu.pp
spec/classes/collectd_plugin_intel_pmu_spec.rb
templates/plugin/intel_pmu.conf.erb

This PR adds support for the intel_pmu plugin.
It supports the parameters that are documented here: https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_intel_pmu
The implementation uses the standard pattern as seen in other plugins using modern puppet types (also seen in other plugins).
I'd be glad to get any feedback on this. Thank you!

Add intel_pmu plugin

---

manifests/init.pp
metadata.json

As discussed #746 here is a PR to fix the data type for package_keyserver.
This is cannot be merged until there is a release of puppetlabs-stdlib that include the proper datatype (it's only on master right now)

feat: use Stdlib::Fqdn type for package_keyserver

---

manifests/plugin/disk.pp
manifests/plugin/sensors.pp
spec/classes/collectd_plugin_disk_spec.rb
spec/classes/collectd_plugin_sensors.rb

We need to be able to specify some options when installing plugins package (e.g. --enablerepo) when we are using Redhat.
Replacement for #664

Install package with options in sensors and disk plugins

---

manifests/config.pp
manifests/install.pp
manifests/service.pp

Those classes are private, they are not supposed to be called directly. The assert_private() methods will throw a compile error if they are accessed from the outside (sadly the Puppet DSL has no concept of public/private classes)

add assert_private to private classes

---

manifests/init.pp
manifests/install.pp

Use variables from init.pp directly

Remove parameters from collectd::install class

---

manifests/plugin.pp
manifests/plugin/aggregation/aggregator.pp
manifests/plugin/apache/instance.pp
manifests/plugin/chain.pp
manifests/plugin/curl/page.pp
manifests/plugin/curl_json.pp
manifests/plugin/dbi.pp
manifests/plugin/exec.pp
manifests/plugin/filecount/directory.pp
manifests/plugin/filter.pp
manifests/plugin/filter/chain.pp
manifests/plugin/genericjmx.pp
manifests/plugin/mysql/database.pp
manifests/plugin/network/listener.pp
manifests/plugin/network/server.pp
manifests/plugin/oracle.pp
manifests/plugin/postgresql.pp
manifests/plugin/processes.pp
manifests/plugin/python.pp
manifests/plugin/python/module.pp
manifests/plugin/rabbitmq.pp
manifests/plugin/snmp/data.pp
manifests/plugin/snmp/host.pp
manifests/plugin/tail/file.pp
manifests/plugin/write_graphite.pp
manifests/typesdb.pp

The $service_name variable exists but is useless as Service['collectd'] is used in most places.
More or less identical to #738 by @fnoop
Fixes #688

Use $collectd::service_name consistently

---

manifests/config.pp

- Remove parameters
- Change default file mode for collectd.conf from 0644 to 0640
- Set owner of collectd.conf to $collectd::config_owner
- Set group of collectd.conf to $collectd::config_group

config.pp clean up

---

manifests/plugin/oracle.pp
manifests/plugin/oracle/database.pp
manifests/plugin/oracle/query.pp

- Also make minor changes for clarity

collectd::plugin::oracle - Use data types

---

manifests/init.pp
manifests/params.pp
spec/classes/collectd_init_spec.rb

- Only allow Boolean for $purge
- Only allow Boolean for $recurse
- Only allow Integer for $write_queue_limit_low
- Only allow Integer for $write_queue_limit_high
- Don't allow undef for $manage_service
- Replace anchors with contain
- Remove some unecessary tests

Use data types, remove anchors

---

manifests/plugin/apache.pp

- $manage_package must now be a Boolean and defaults to the value of $collectd::manage_package

collectd::plugin::apache - Use data types

---

manifests/plugin/amqp.pp
spec/classes/collectd_plugin_amqp_spec.rb
types/amqp/format.pp

- $manage_package must now be a Boolean and defaults to the value of $collectd::manage_package
- $amqpport cannot be a String

collectd::plugin::amqp - Use data types

---

templates/plugin/python/module.conf.erb

This PR removes array sorting in python module template
We need to keep the array order provided by the config parameter of the collectd::plugin::python::module function parameter instead of an alphabetic order.
Please see #586 for details.
Fixes #586

Remove array sorting in python module template (#586)

---

spec/defines/collectd_plugin_snmp_data_spec.rb
spec/defines/collectd_plugin_snmp_host_spec.rb
templates/plugin/snmp.conf.erb

Avoid creating lines with trailing white-spaces in the snmp configuration file.
n/a

Fix trailing spaces

---

manifests/plugin/bind.pp
spec/classes/collectd_plugin_bind_spec.rb
types/bind/view.pp

This tiny Pull-Request add a custom type for validating the values passed to `$collectd::plugin::bind::views`.  Without this safety belt, you can end up with a useless (but surprisingly valid!) configuration file:
```
<Plugin bind>
[...]
<View "">
</View>
<View "">
</View>
</Plugin>
```
n/a

Validate bind view parameters

---

README.md

doc: tell rake rubocop is needed
"rake rubocop" is missing comparing of what ran on travis-ci.
Adds it, so contributor will not missing syntax issue with old puppet
version.

doc: tell rake rubocop is needed

---

manifests/plugin/amqp1.pp
spec/classes/collectd_plugin_amqp1_spec.rb
templates/plugin/amqp1.conf.epp

This patch adds possibility to configure amqp1 plugin added recently
to collectd [1].
[1] https://github.com/collectd/collectd/pull/2618

Add amqp1 plugin support

---

metadata.json

CentOS 6 is too old, the provided packages in epel don't work anymore
with the module. Some failures can be seen at https://github.com/voxpupuli/puppet-collectd/pull/807

drop centos 6 support

---

README.md
spec/acceptance/class_plugin_python_spec.rb
spec/classes/collectd_plugin_python_spec.rb
spec/spec_helper_acceptance.rb

A collectd::plugin::python acceptance test

A collectd::plugin::python acceptance test

---

README.md
spec/classes/collectd_plugin_python_spec.rb
templates/plugin/python/module.conf.erb

With a configuration of
```puppet
collectd::python::python{'foo':
modules => { 'foo' => { config => [{'value' => 4}]
}
}
}
```
Puppet fails with `undefined method scan for 4:Fixnum`.
Integers and floats are now accepted and displayed as numbers.
Fixes #662

Fixes #662 accept numbers into configuration file

---

README.md
manifests/plugin/ipc.pp

Add ipc plugin
Collectd plugin ipc have been added in Collectd 5.5.
This change adds its support to puppet-collectd

Add ipc plugin

---

README.md
manifests/plugin/powerdns.pp
manifests/plugin/powerdns/recursor.pp
manifests/plugin/powerdns/server.pp
spec/classes/collectd_plugin_powerdns_spec.rb
templates/plugin/powerdns-header.conf.epp
templates/plugin/powerdns/recursor.conf.epp
templates/plugin/powerdns/server.conf.epp

Add powerdns plugin

---

README.md
functions/indent.pp
manifests/plugin/threshold.pp
spec/classes/collectd_plugin_threshold_spec.rb
templates/plugin/threshold.conf.epp
templates/plugin/threshold/host.epp
templates/plugin/threshold/plugin.epp
templates/plugin/threshold/type.epp
types/threshold/host.pp
types/threshold/plugin.pp
types/threshold/type.pp

Allow to configure the threshold plugin
```puppet
class { 'collectd::plugin::processes':
process_matches => [
'carbon-cache',
'python.+carbon-cache',
],
}
class { 'collectd::plugin::threshold':
plugins => {
processes => {
instance => 'carbon-cache',
types    => {
data_source => 'processes',
warning_min => 2,
failure_min => 1,
},
},
},
}
```
Fixes #292

Make the threshold plugin configurable

---

manifests/plugin/connectivity.pp
manifests/plugin/procevent.pp
manifests/plugin/sysevent.pp
spec/classes/collectd_plugin_connectivity_spec.rb
spec/classes/collectd_plugin_procevent_spec.rb
spec/classes/collectd_plugin_sysevent_spec.rb
templates/plugin/connectivity.conf.epp
templates/plugin/procevent.conf.epp
templates/plugin/sysevent.conf.epp

This patch adds support for NFVPE plugins, namely: sysevent, procevent and connectivity. 
Those plugins are not merged yet in collectd itself, but once this (hopefully) happens, 
we will have configuration patch ready for merge. 
Collectd patches:
https://github.com/collectd/collectd/pull/2624
https://github.com/collectd/collectd/pull/2623
https://github.com/collectd/collectd/pull/2622
n/a

Configuration for NFVPE plugins

---

manifests/init.pp
manifests/params.pp
spec/classes/collectd_init_spec.rb
templates/collectd.conf.erb

This PR adds adding AutoLoadPlugin to global options. Usually, it should be disabled.

add AutoLoadPlugin to global options

---

Gemfile
spec/spec_helper_acceptance.rb

update gem dependencies

---

templates/curl_json.conf.erb

Configuration file right now is being created with a wrong format since for the Host parameter there is an extra ">"

Fix wrong closure of Host parameter for curljson template

---

spec/acceptance/class_spec.rb
spec/acceptance/curl_json_spec.rb

`fact` no longer works with symbols.

Fix beaker tests

---

spec/classes/collectd_plugin_postgresql_spec.rb
templates/plugin/postgresql/database.conf.erb

When passing it as a string the plugin will basically ignore the setting and write the following to the log file:
```
cf_util_get_cdtime:
The Interval option requires exactly one numeric argument.
```
Without this patch it's not possible to declare different databases with different query interval.

Persist the interval in the conf file as a number

---

examples/plugins/memcached.pp
manifests/plugin/memcached.pp
spec/classes/collectd_plugin_memcached_spec.rb
templates/plugin/memcached.conf.erb

As addition to the host field, there is also the address setting,
which is helpful sometimes.
This also adds the address field to the memcached plugin.

Add address field to memcached plugin

---

manifests/plugin/aggregation.pp
manifests/plugin/curl.pp
manifests/plugin/dbi.pp
manifests/plugin/exec.pp
manifests/plugin/filecount.pp
manifests/plugin/network.pp
manifests/plugin/postgresql.pp
manifests/plugin/powerdns.pp
manifests/plugin/processes.pp
manifests/plugin/python.pp
manifests/plugin/tail.pp
manifests/plugin/write_graphite.pp

Replace create_resources with resource types
Fixes #716 (Replace create_resources() calls)

replace create_resources with resource types

---

README.md
metadata.json
tasks/getval.json
tasks/getval.py
tasks/listval.json
tasks/listval.py

Two puppet tasks
* collectd::listval - lists all collectd metrics on a node
* collectd::getval metric=load/load-relative - shows values
of a particular metric
For example
```bash
$ bolt -u root task run collectd::getval metric=load/load-relative -n node.example.org
Started on node.example.org...
Finished on node.example.org:
{
"metric": "load/load-relative",
"values": {
"shortterm": "1.750000e-01",
"longterm": "8.000000e-02",
"midterm": "8.500000e-02"
}
}
```

Add puppet tasks to call collectdctl

---

manifests/plugin/perl/plugin.pp

When using the perl plugin the following issue is raised during catalog compilation, upon inspection this appears to be declared from variable which is not used, so removing it seemed the most logic resolution.
`error during compilation: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown variable: 'collectd::plugin::perl::filename'.`

remove reference to collectd::plugin::perl::filename

---

README.md
lib/facter/python_dir.rb
spec/unit/python_dir_spec.rb

RHEL8 in particular has no python command by design
attempt to use python3 if there is no python command.
https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/

Accept to use python3 if python is not on the path

---

manifests/plugin/curl_json.pp
spec/defines/collectd_plugin_curl_json_spec.rb

We don't support Ubuntu Precise (12.04) anymore, so we can remove the
legacy code.

drop legacy precise code

---

manifests/repo/debian.pp
spec/classes/collectd_init_spec.rb

Hi
It seems to me that there is not any dependency between Exec['apt_update'] and Package['collectd'].
Specifically, this is what I get in `noop` mode: `apt-update` is run after the installation of the `collectd` package.
```
Notice: Compiled catalog for 067d02440e1f in environment production in 0.48 seconds
Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: current_value absent, should be file (noop)
Notice: Apt::Setting[conf-update-stamp]: Would have triggered 'refresh' from 1 events
Notice: /Stage[main]/Apt/File[preferences]/ensure: current_value absent, should be file (noop)
Notice: Class[Apt]: Would have triggered 'refresh' from 2 events
Notice: Class[Collectd::Repo::Debian]: Would have triggered 'refresh' from 1 events
Notice: …
```

Apt update before installation of collectd

---

manifests/plugin/write_graphite/carbon.pp
templates/plugin/write_graphite/carbon.conf.erb

Version 5.6 has introduced the ReconnectInterval option to the write_graphite plugin (https://collectd.org/wiki/index.php/Version_5.6).
ReconnectInterval Seconds
When set to non-zero, forces the connection to the Graphite backend to be closed and re-opend periodically. This behavior is desirable in environments where the connection to the Graphite backend is done through load balancers, for example. When set to zero, the default, the connetion is kept open for as long as possible.
(https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_write_graphite)
New feature

Add ReconnectInterval option to the write_graphite plugin (defaults to zero, introduced in version 5.6)

---

manifests/plugin/procevent.pp
spec/classes/collectd_plugin_procevent_spec.rb
templates/plugin/procevent.conf.epp

review. It is now named ProcessRegex.
See https://github.com/collectd/collectd/blob/master/src/procevent.c#L1227
Fixes #897

RegexProcess has been renamed during collectd

---

README.md
manifests/plugin/mcelog.pp
spec/classes/collectd_plugin_mcelog_spec.rb
templates/plugin/mcelog.conf.epp
types/mcelog/memory.pp

Intel Mcelog plugin https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_mcelog

Add Mce log plugin

---

manifests/plugin/java.pp
spec/classes/collectd_plugin_java_spec.rb

`collectd-java` requires:
* `libjvm.so()(64bit)`
* `libjvm.so(SUNWprivate_1.1)(64bit)`
On CentOS/RHEL 6.x/7.x these are provided by OpenJDK. OpenJDK stores the
JVM files in a bit of a different location: `amd64` has been removed
from the path. Thus, ATM the link does not get created properly on such
systems.
Fix this problem by adding two `exec` resources which both will try to
create the needed libjvm symbolic link. They are both smart and check if
that file exists before trying to execute. An assumption is added to the
code that both of the files cannot exist at the same time.

plugin/java: handle OpenJDK as well

---

manifests/plugin/mcelog.pp
spec/classes/collectd_plugin_mcelog_spec.rb

Plugin Mcelog default config

---

README.md
manifests/plugin/snmp_agent.pp
spec/classes/collectd_plugin_snmp_agent_spec.rb
templates/plugin/snmp_agent.conf.epp
types/snmp_agent/data.pp
types/snmp_agent/indexkey.pp
types/snmp_agent/table.pp

Snmp agent plugin manifest templates and tests.

Add SNMP agent plugin

---

.fixtures.yml
metadata.json

stahnma-epel has now migrated to VoxPupuli
name space.
Also in particular the `puppet-epel` version is requirment to
work with CentOS 8.

Require puppet-epel over stahnma-epel

---

.sync.yml
.travis.yml
README.md
lib/facter/python_dir.rb
manifests/params.pp
manifests/plugin/cuda.pp
manifests/plugin/iscdhcp.pp
manifests/plugin/python.pp
manifests/plugin/rabbitmq.pp
metadata.json
spec/acceptance/class_plugin_python_spec.rb
spec/acceptance/class_spec.rb
spec/acceptance/curl_json_spec.rb
spec/classes/collectd_plugin_rabbitmq_spec.rb
spec/spec_helper_acceptance.rb
spec/spec_helper_methods.rb

Add CentOS 8 support
The main differences for CentOS 8 are:
* There is now a new collectd-utils package containing collectdctl
* collectd-python is now a seperate sub package
* python is python3.
* pip command is now pip3
* The rabbitmq plugin no longer works due to lack of python3 support
The `python_dir` fact will fall back to `/usr/libexec/platform-python`
if `python3` does not exist on the path. This is the python
that collectd uses and  significantly all that collectd-python requires.
Note that setting `collectd::ci_package_repo` true will currently
result in yum being configured with a non existant repo since
https://pkg.ci.collectd.org/rpm/ does not exist
for 8.  [request](https://github.com/collectd/collectd-ci/issues/35)

Add CentOS 8 support

---

manifests/init.pp
manifests/install.pp
manifests/params.pp
spec/acceptance/class_plugin_python_spec.rb
spec/classes/collectd_init_spec.rb

On some operating systems `collectdctl`, `collectd-nagios`
is contained in a seperate sub package, typically `collectd-utils`
Setting `utils` to `true` will install this sub package if it exists
for an operating system.
Also start some puppet-strings.

New utils parameter to install collectdctl

---

CHANGELOG.md
metadata.json

Release 11.3.0
Introduces first CentOS 8 support in particular.

Release 11.3.0

---

spec/unit/python_dir_spec.rb

The unit tests for python_dir fact were giving a false failure
```
1) python_dir is empty string if python not installed
Failure/Error: expect(Facter.fact(:python_dir).value).to eq('')
expected: ""
got: "/usr/lib/python2.7/site-packages"
(compared using ==)
```
If they were executed on a system where `/usr/libexec/platform-python`
was present - not the case (presumably) for Travis CI.

Ignore more installed versions of python during tests

---

spec/acceptance/class_plugin_load_spec.rb
templates/plugin/load.conf.erb

Re-fixes https://github.com/voxpupuli/puppet-collectd/issues/901
The bug was that a ReportRelative configuration to the load
plugin for collectd 5.9.o was causing a parse error.
collectd module now skips this configuration for collectd for collectd == 5.9.0
Previously it was '!=' 5.9.
* Upsteam bug for collectd: https://github.com/voxpupuli/puppet-collectd/issues/901
* Previous incorrect commit: https://github.com/voxpupuli/puppet-collectd/commit/8edc01430d03eeabe812a7bab065f6b25200fda3

Skip Load:ReportRelative as problematic for collectd 5.9.0

---

manifests/plugin/processes.pp
manifests/plugin/processes/process.pp
manifests/plugin/processes/processmatch.pp
spec/acceptance/define_plugin_processes_process_spec.rb
spec/acceptance/define_plugin_processes_processmatch_spec.rb
spec/classes/collectd_plugin_processes_spec.rb

There was a name clash between:
* Puppet created configuration file.
* Package provided configuration file.
Since a864d0d58815d58c944277417dcf52df2d3c7572 the collectd module on RedHat
purges the package provided file file `/etc/collectd.d/processes-config.conf`
The module was also creating this file with a concat and result was no
file on system.
To avoid the clash puppet now creates the file `processes_config.conf`. Note
the `-` vs `_`.
There is probably a cleaner fix to move all of the processes plugin configuration
into the per module file `/etc/collect.d/10-processses.conf` as that would
be more consistant with other simpler modules. This would be a change
for every module however with `collectd::plugin` itself changing.
Fixes #926

Create processes plugin configuration on RedHat

---

manifests/plugin/amqp1.pp
manifests/plugin/dns.pp
manifests/plugin/hddtemp.pp
manifests/plugin/mongodb.pp
manifests/plugin/mysql/database.pp
manifests/plugin/network/listener.pp
manifests/plugin/network/server.pp
manifests/plugin/ntpd.pp
manifests/plugin/ovs_events.pp
manifests/plugin/ovs_stats.pp
manifests/plugin/postgresql/database.pp
manifests/plugin/statsd.pp
manifests/plugin/tcpconns.pp
manifests/plugin/write_graphite/carbon.pp
manifests/plugin/write_kafka.pp
manifests/plugin/write_prometheus.pp
manifests/plugin/write_sensu.pp
manifests/plugin/write_tsdb.pp
manifests/plugin/zookeeper.pp
spec/classes/collectd_plugin_amqp1_spec.rb
spec/classes/collectd_plugin_mongodb_spec.rb
spec/classes/collectd_plugin_mysql_database_spec.rb
spec/classes/collectd_plugin_postgresql_spec.rb
spec/classes/collectd_plugin_statsd_spec.rb
spec/classes/collectd_plugin_write_kafka_spec.rb
spec/classes/collectd_plugin_write_prometheus_spec.rb
spec/classes/collectd_plugin_zookeeper_spec.rb
types/redis/node.pp

Instead of having a mix of strings and integers, all port parameters
should be using `Stdlib::Port`.
I've also changed some `String`s to `Stdlib::Host`, but none of these
should be breaking changes.

Change all `port` parameters to use `Stdlib::Port`

---

CHANGELOG.md
metadata.json

release 12.1.0

---

manifests/plugin/unixsock.pp
spec/classes/collectd_plugin_unixsock_spec.rb

The default path for unixsock has been /var/run/collectd-unixsock since
the first version of the plugin, 14 years ago:
https://github.com/collectd/collectd/blob/4bf284162200a304f0ec8d1f5c2dd93339ddc64c/src/unixsock.c#L48
This path is not overridden by the Debian nor CentOS packages as
installed by the module.
Use this path by default so that collectdctl without argument can
connect to the socket, unbreaking the bolt tasks.
n/a

Fix unixsock default path

---

templates/plugin/python/module.conf_config.epp

Simplified the epp template contained:
```erb
<%# a comment #%>
```
* In puppet 5 this renders as a new line. The prefix of spaces is eaten and a new line is created.
* In puppet 6 this renders as a string of spaces and new line.
The puppet 6 behaviour is better so I expect a bug was fixed sometime.
In reality there should be no spaces in here so change to
```erb
<%#- a comment -%>
```
which renders as nothing and gives us zero catalogue change between 5 and 6 :-)
Extra commit also to remove a redundant blank line from `python-config.conf`

Remove redundant white space from python templates

---

manifests/plugin/dbi/database.pp
spec/classes/collectd_plugin_dbi_spec.rb
templates/plugin/dbi/database.conf.erb

By default dpi plugin and each database querying configuration inherits global collectd Interval. While this global interval may be OK for some mail queue checking activities, it is overwhelmingly frequent as for a daily check on a number of email accounts through mysql database. Since collectd [dbi plugin ](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_dbi) support Interval, I would like to have it added into puppet module as well.
P.S. Checked puppet code through` puppet validate` and ruby template syntax/rendering through 
`erb db_query_interval=120 -P -x -T '-' templates/plugin/dbi/database.conf.erb`
Please consider my pull request.

Allow to set separate interval for database resource

---

.sync.yml
Gemfile
spec/spec_helper.rb
spec/unit/collectd_real_version_spec.rb
spec/unit/python_dir_spec.rb

This PR converts the rspec tests used for testing the fact to rspec, rather than mocha, to match the other voxpupuli modules.

Convert mocha tests to rspec

---

manifests/plugin/virt.pp
spec/classes/collectd_plugin_virt_spec.rb
templates/plugin/virt.conf.erb

Add the PluginInstanceFormat parameter to the virt plugin to allow for specifying the
plugin instance format, resulting in a new label being available to the virt metrics. By
adding this you can provide the UUID of the virtual machine, along with HostnameFormat
to have information about VMs that exist per physical host.

Add PluginInstanceFormat parameter to virt plugin

---

manifests/plugin/protocols.pp
spec/classes/collectd_plugin_protocols_spec.rb
templates/plugin/protocols.conf.erb

Fix `ignoreselected` typo in protocols.conf.erb template

---

templates/plugin/dbi/query.conf.erb

Without this change collectd refuse to load configuration for dbi plugin with error (at least for me - collectd-5.8.1):
The Query block needs exactly one string argument.
dbi plugin: No <Query> blocks have been found. Without them, this plugin can't do anything useful, so we will return an error.

Fix dbi query.conf.erg template

---

manifests/plugin/mcelog.pp
spec/classes/collectd_plugin_mcelog_spec.rb

Similar to `collectd-sensors`, redhat systems need `collectd-mcelog` package to be installed.
Fixes issue when collectd fails with `plugin_load: Could not find plugin "mcelog" in /usr/lib64/collectd`

Install collectd-mcelog package on RedHat

---

spec/classes/collectd_plugin_python_spec.rb
spec/defines/collectd_plugin_python_module_spec.rb
templates/plugin/python/module.conf_config.epp

Collectd expects to have a single value per each key when it is not another Config object instance included within the module configuration. So the result from an array of params is supposed to be like.
Key "Value1"
Key "Value 2"
Key 22
Key false
Change of module configuration parsing array values to per single value fixes the issue.
Fixes #964

Separation of values for a python plugin array module key

---

spec/classes/collectd_plugin_virt_spec.rb
templates/plugin/virt.conf.erb

Use of double-quotes around the HostnameFormat field in the virt plugin erb
template is wrong when using multiple names. Error generated will be
[2020-09-04 03:17:04] virt plugin: unknown HostnameFormat field: name metadata uuid
when setting the configuration to
HostnameFormat "name metadata uuid"
Simply removing the double quotes allows for a successful virt plugin load. Source
in collectd justifying this change is at: https://github.com/collectd/collectd/blob/main/src/virt.c#L834
Fixes #953

Drop erroneous double quotes from virt plugin template

---

manifests/plugin/virt.pp
spec/classes/collectd_plugin_virt_spec.rb

The plugin_instance_format (PluginInstanceFormat) parameter in the
collectd virt plugin is capable of taking multiple values, not a single
value from an Enum list.
Fixes #968

Convert plugin_instance_format from Enum to String

---

manifests/plugin/write_graphite/carbon.pp
templates/plugin/write_graphite/carbon.conf.erb

In version 5.9.0 of collectd, a ReverseHost parameters was added to the write_graphite plugin.  If set to **true**, the (dot separated) parts of the host field of the value list will be rewritten in reverse order. The rewrite happens before special characters are replaced with the EscapeCharacter.
Feature is currently unavailable when using the module

Adding Reverse Host parameter

---

spec/classes/collectd_plugin_postgresql_spec.rb
templates/plugin/postgresql/database.conf.erb

Previously, databases configured with a writer query would not regularly commit collected data.
This PR makes the postgresql configuration template emit the stanza `CommitInterval` instead of just `Interval` when a database is configured with a writer query, fixing the problem.
Fixes #971

Emit CommitInterval when writer is configured for database

---

.fixtures.yml
metadata.json

Drop EoL Puppet 5 support; Add Puppet 7 support / Allow latest dependencies / Drop EoL Debian 8

---

.github/workflows/ci.yml
Gemfile

This is a test to check if Ruby 3.0 already works

CI: Run on Ruby 3.0 instead of 2.7

---

.sync.yml

We had this in the past, but it was purged by accident in a previous
msync run:
https://github.com/voxpupuli/puppet-collectd/commit/c5e7f6d1d00c7bce637b31118873773a4a9aa9ff#diff-b1bbc4d50c1c098ca18224cbc9519ad646dcc5e3dd912edf55610ab5bba3566eL12-L13

.sync.yml: load spec_helper_methods in spec_helper.rb

---

.sync.yml

#979 introduced a line with 3 spaces instead of 2.  It is the root cause of this error:
https://github.com/voxpupuli/modulesync_config/pull/732/checks?check_run_id=3247404546
Running `msync update` with the `--offline` flag after fixing this space problem does not fail.
n/a

Fix spacing in YAML file

---

.sync.yml

ceacd462bb6150774b3acaf8df48a535a7fba0a8 attempted to fix this, but this is a change I needed to make. I'm not sure what the exact difference is, but it's clearly there.

Fix whitespace in .sync.yml

---

manifests/plugin/cuda.pp
manifests/plugin/iscdhcp.pp
manifests/plugin/rabbitmq.pp
metadata.json
spec/classes/collectd_plugin_rabbitmq_spec.rb
spec/spec_helper_methods.rb

Add ubuntu 20 support

---

metadata.json

Arch doesn't have the collectd package in the official repos anymore.

Drop Arch Linux support

---

manifests/config.pp
spec/classes/collectd_plugin_dbi_spec.rb
spec/classes/collectd_plugin_exec_spec.rb
spec/classes/collectd_plugin_genericjmx_spec.rb
spec/classes/collectd_plugin_postgresql_spec.rb
spec/classes/collectd_plugin_powerdns_spec.rb
spec/classes/collectd_plugin_processes_spec.rb
spec/classes/collectd_plugin_python_spec.rb
spec/classes/collectd_plugin_write_graphite_spec.rb
spec/defines/collectd_plugin_filter_chain_spec.rb

Previously all the concat's created typically in /etc/collect.d were subject to
File['collectd.d'] -> Concat <| tag == 'collectd' |>
to ensure the directory was in place first.
This turns out to be too greedy and can cause problems as per #1000.
This declaration is unnecessary as concat creates a file type
and this auto-requires the directory one level above.
Fixes #1000

Rely on autorequires of files when using concat

---

metadata.json

This allows us to support EL9 systems in a later PR.
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>

puppet/epel: Allow 4.x

---

manifests/plugin/ceph.pp
spec/classes/collectd_plugin_ceph_spec.rb
templates/plugin/ceph.conf.erb

Ceph 16 onwards sockets for Ceph services are placed under '/var/run/ceph/\<fsid\>/'
This change introduces a new variable `ceph_fsid` to hold Ceph cluster's fsid which must be of type string.
Configuration file for ceph plugin will be generated with new path only if `ceph_fsid` is set.
n/a
Signed-off-by: Yadnesh Kulkarni <ykulkarn@redhat.com>

Update socket path of ceph services in ceph plugin

---

manifests/plugin/curl.pp
manifests/plugin/mysql.pp
manifests/plugin/postgresql.pp
manifests/plugin/snmp.pp

If you attempt to specify the collectd version in Hiera, and a newer version is available, issue might be caused because the package install of the plugins on new hosts would install the latest version for both the plugin and the main package (as a dependency). Puppet then starts failing attempting to downgrade the main package to your specified version.
With this PR it is ensure that mysql, snmp, postgresql and curl, are installed with the same version as the core package. Same thing was done for the disk plugin some time ago: https://github.com/voxpupuli/puppet-collectd/blob/master/manifests/plugin/disk.pp#L26L37
Partially fixes #430

Ensure plugin version is same version as main collectd package

---

README.md
REFERENCE.md
examples/plugins/write_prometheus.pp
manifests/plugin/write_prometheus.pp
spec/classes/collectd_plugin_write_prometheus_spec.rb
templates/plugin/write_prometheus.conf.erb

The option was introduced in version 5.9 of collectd

Add support for the Host option for the write_prometheus plugin

---

REFERENCE.md
manifests/plugin/table.pp
manifests/plugin/table/table.pp
spec/acceptance/define_plugin_table_table_spec.rb
spec/defines/collectd_plugin_table_table_spec.rb
templates/plugin/table.conf.epp

For example to parse `/proc/uptime` with the collectd table plugin can now be defined with:
```
collectd::plugin::table::table{'/proc/uptime':
table =>  {
'plugin'    => 'uptime',
'instance'  => 'first',
'separator' => ' ',
'results' => [{
'type'        => 'gauge',
'values_from' => [0],
}],
}
}
```
Previously it was only possible to specify tables at one location with the class `collectd::plugin::table`. The class `collectd::plugin::table` remains unchanged.

New collectd::plugin::table::table type

---

lib/facter/collectd_version.rb
spec/fixtures/facts/collectd_help_git_plus
spec/unit/collectd_real_version_spec.rb

The version string resulting from a `make dist` of collectd may contain a +, e.g. 5.12.0.167.g7c5ce9f+, from being run on a dirty working tree.

Accept + in collectd_version Fact

---

.sync.yml
spec/classes/collectd_init_spec.rb
spec/classes/collectd_plugin_apache_spec.rb
spec/classes/collectd_plugin_disk_spec.rb
spec/classes/collectd_plugin_java_spec.rb
spec/classes/collectd_plugin_mcelog_spec.rb
spec/classes/collectd_plugin_netlink_spec.rb
spec/classes/collectd_plugin_ovs_events_spec.rb
spec/classes/collectd_plugin_ovs_stats_spec.rb
spec/classes/collectd_plugin_processes_spec.rb
spec/classes/collectd_plugin_rabbitmq_spec.rb
spec/classes/collectd_plugin_rrdtool_spec.rb
spec/classes/collectd_plugin_smart_spec.rb
spec/classes/collectd_plugin_virt_spec.rb
spec/classes/collectd_plugin_write_http_spec.rb
spec/spec_helper.rb
spec/spec_helper_methods.rb

also contains https://github.com/voxpupuli/puppet-collectd/pull/1045

facterdb_string_keys: switch to strings
